-- Create user for Employee
alter session set "_oracle_script"=true;
create user NV01 identified by NV01;
grant create session to NV01;
create user NV02 identified by NV02;
grant create session to NV02;
create user NV03 identified by NV03;
grant create session to NV03;
create user NV04 identified by NV04;
grant create session to NV04;
create user NV05 identified by NV05;
grant create session to NV05;
create user NV06 identified by NV06;
grant create session to NV06;
create user NV07 identified by NV07;
grant create session to NV07;
create user NV08 identified by NV08;
grant create session to NV08;
create user NV09 identified by NV09;
grant create session to NV09;
create user NV10 identified by NV10;
grant create session to NV10;
create user NV11 identified by NV11;
grant create session to NV11;
create user NV12 identified by NV12;
grant create session to NV12;
create user NV13 identified by NV13;
grant create session to NV13;
create user NV14 identified by NV14;
grant create session to NV14;
create user NV15 identified by NV15;
grant create session to NV15;
create user NV16 identified by NV16;
grant create session to NV16;
create user NV17 identified by NV17;
grant create session to NV17;
create user NV18 identified by NV18;
grant create session to NV18;
create user NV19 identified by NV19;
grant create session to NV19;
create user NV20 identified by NV20;
grant create session to NV20;
create user NV21 identified by NV21;
grant create session to NV21;
create user NV22 identified by NV22;
grant create session to NV22;
create user NV23 identified by NV23;
grant create session to NV23;
create user NV24 identified by NV24;
grant create session to NV24;
create user NV25 identified by NV25;
grant create session to NV25;
create user NV26 identified by NV26;
grant create session to NV26;
create user NV27 identified by NV27;
grant create session to NV27;
create user NV28 identified by NV28;
grant create session to NV28;
create user NV29 identified by NV29;
grant create session to NV29;
create user NV30 identified by NV30;
grant create session to NV30;
create user NV31 identified by NV31;
grant create session to NV31;
create user NV32 identified by NV32;
grant create session to NV32;
create user NV33 identified by NV33;
grant create session to NV33;
create user NV34 identified by NV34;
grant create session to NV34;
create user NV35 identified by NV35;
grant create session to NV35;
create user NV36 identified by NV36;
grant create session to NV36;

-- Create user  for ProjectManager
create user PM01 identified by PM01;
grant create session to PM01;
create user PM02 identified by PM02;
grant create session to PM02;
create user PM03 identified by PM03;
grant create session to PM03;
create user PM04 identified by PM04;
grant create session to PM04;
create user PM05 identified by PM05;
grant create session to PM05;

-- Create user for DepartmentChief
create user DC01 identified by DC01;
grant create session to DC01;
create user DC02 identified by DC02;
grant create session to DC02;
create user DC03 identified by DC03;
grant create session to DC03;
create user DC04 identified by DC04;
grant create session to DC04;
create user DC05 identified by DC05;
grant create session to DC05;

-- Create user for BarnchManager
create user BM01 identified by BM01;
grant create session to BM01;
create user BM02 identified by BM02;
grant create session to BM02;
create user BM03 identified by BM03;
grant create session to BM03;
create user BM04 identified by BM04;
grant create session to BM04;
create user BM05 identified by BM05;
grant create session to BM05;

-- Create user for Director
create user D01 identified by D01;
grant create session to D01;
create user D02 identified by D02;
grant create session to D02;
create user D03 identified by D03;
grant create session to D03;
create user D04 identified by D04;
grant create session to D04;
create user D05 identified by D05;
grant create session to D05;
